# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180507_1402'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartmodel',
            table='axf_cart',
        ),
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtypes',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='axf_goods',
        ),
        migrations.AlterModelTable(
            name='mustbuy',
            table='axf_mustbuy',
        ),
        migrations.AlterModelTable(
            name='nav',
            table='axf_nav',
        ),
        migrations.AlterModelTable(
            name='ordergoodsmodel',
            table='axf_order_goods',
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table='axf_order',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='axf_shop',
        ),
        migrations.AlterModelTable(
            name='show',
            table='axf_mainshow',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='axf_user',
        ),
        migrations.AlterModelTable(
            name='wheel',
            table='axf_wheel',
        ),
    ]
