# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_userticketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticketmodel',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userticketmodel',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.UserModel'),
        ),
    ]
